# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases/hr.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseHr(HttpRunner):

    config = Config("微信授权登录").export(*["token"])

    teststeps = [
        Step(
            RunRequest("微信授权登录")
            .post("https://api.fanshouhou.com/business/login/wxlogin")
            .with_data({"code": "011Ss60w3SkqlV2g9r3w30Vqj20Ss60V"})
            .extract()
            .with_jmespath("headers.Authorization", "token")
            .validate()
            .assert_equal("status.code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseHr().test_start()
